dataset:
  data_dir: '/scratch/iew/sthv2/tokens/vqgan/train'
  embed_model_path: './imagenet_k600.ckpt'
  la_path: './latent_action.pth'
    
model:
  in_dim:
    value: 8
  model_dim:
    value: 128
  latent_dim:
    value: 7
  enc_blocks:
    value: 2
  dec_blocks:
    value: 2
  num_heads:
    value: 8
  dropout:
    value: 0.2
  global_patch:
    value: True